<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_keterangan</name>
   <tag></tag>
   <elementGuidId>8d94c1ad-7bc6-49df-9c82-aa5e088fe6b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02961807-2d95-4dd8-ae96-2ecc282bf0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cd</value>
      <webElementGuid>346c79cd-6182-42c1-ab5a-c00900a38874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2fcaa156-c71f-4df8-80e9-7fa2f061bf53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_description</value>
      <webElementGuid>2e85dedd-da4a-4309-a8a8-a70e65e76033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>919e84ca-2f52-4f48-8c73-618de922522e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-errormessage-value-missing</name>
      <type>Main</type>
      <value>Data tidak boleh kosong!</value>
      <webElementGuid>3a18a776-f9c7-4d74-b587-4336438c100b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cd&quot;)</value>
      <webElementGuid>9e08f32e-6fa1-4675-aff5-d1fd29c5451a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/page_tambah_kategori/iframe_Tester_title</value>
      <webElementGuid>9a69f0bc-15e9-4973-8646-5376c8e59f3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cd']</value>
      <webElementGuid>8b7a0ea5-c316-4401-af5e-e0173428860b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>b2a33ddf-ff6f-4f38-98a5-5c7ae0cbb8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cd' and @type = 'text' and @name = 'category_description']</value>
      <webElementGuid>90fd34b0-c415-41da-9523-63c01cd1dbcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
