<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_judul_kategori</name>
   <tag></tag>
   <elementGuidId>bc469e26-8640-471a-8cf3-92bcc10388fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='category_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;category_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b662ad0-6c8a-451e-a46c-f673d1e28fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7da65186-d6e9-4821-9d0d-290b7eaccdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_name</value>
      <webElementGuid>98241068-7156-41e7-9aa3-7bee889134ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>24adbde5-8795-40b1-afb3-dc92f31ef5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-errormessage-value-missing</name>
      <type>Main</type>
      <value>Data tidak boleh kosong!</value>
      <webElementGuid>ad4b2a46-1f1a-47ee-b098-dcf986cee29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[2]/td[1]/form[1]/table[@class=&quot;index&quot;]/tbody[1]/tr[2]/td[2]/input[1]</value>
      <webElementGuid>0ac9da9f-0afe-4c74-8553-cf60b7c83f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/page_tambah_kategori/iframe_Tester_title</value>
      <webElementGuid>dd35822e-1e5b-4b88-9054-652835e24a5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='category_name']</value>
      <webElementGuid>9041eddc-1147-41f9-9384-ae1ac399d7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>4ba77633-ed21-469f-9e88-4bbf59a46ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'category_name']</value>
      <webElementGuid>86acd9f6-5de0-4be2-b42a-3f82efb542b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
